ignore_merge_commits = true
tag_prefix = "v"

pre_bump_hooks = []
post_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [{ signature = "Kristof Mattei", username = "kristof-mattei" }]
template = "remote"
remote = "github.com"
repository = "rust-seed"
owner = "kristof-mattei"

[bump_profiles]
