# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Semgrep

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "41 3 * * 6"

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep:1.146.0@sha256:15c3954ba7e0f8ade909e021d85a7c448909d25e1453a1f3e2d3fe8ec2bd5800

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          show-progress: false

      - name: Run semgrep
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: |
          semgrep ci --sarif --output=semgrep.sarif

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        if: |
          always()
        uses: github/codeql-action/upload-sarif@5d4e8d1aca955e8d8589aabd499c5cae939e33c7 # v4.31.9
        with:
          sarif_file: semgrep.sarif
