name: Semgrep

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "41 3 * * 6"

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep:1.66.0@sha256:2fd35fa409f209e0fea0c2d72cf1e5b801a607959a93b13d04822bb3b6a9dfe4

    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          show-progress: false

      - name: Run semgrep
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: |
          semgrep ci --sarif --output=semgrep.sarif

      - name: Upload artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: semgrep.sarif # name of the artifact
          path: semgrep.sarif # path of the file to be part of the artifact (think file added to a zip)

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs:
      - scan

    steps:
      # this checkout satisfies github/codeql-action's need for certain variables to link the sarif to the right commit sha
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          show-progress: false

      - name: Download artifact
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          name: semgrep.sarif # name of the artifact
          path: . # WHERE to unpack all files part of the artifact

      - name: Fixup semgrep.sarif's startColumn==0 and/or endColumn==0
        shell: bash
        run: |
          jq '.' semgrep.sarif > normalized.sarif
          jq 'del(.runs[].results[].locations[].physicalLocation.region | select(.startColumn==0) | .startColumn)' normalized.sarif > fixed_start_column.sarif
          jq 'del(.runs[].results[].locations[].physicalLocation.region | select(.endColumn==0) | .endColumn)' fixed_start_column.sarif > fixed_start_end_column.sarif

          diff normalized.sarif fixed_start_end_column.sarif || true

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        if: always()
        uses: github/codeql-action/upload-sarif@1b1aada464948af03b950897e5eb522f92603cc2 # v3.24.9
        with:
          sarif_file: fixed_start_end_column.sarif
